apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2025.12.4
      helm:
        valueFiles:
          - $myrepo/apps/authentik/values.yaml
    - repoURL: https://github.com/DaltonBuilds/homelab-gitops
      targetRevision: main
      ref: myrepo
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
