apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DaltonBuilds/homelab-gitops.git
    targetRevision: main
    path: apps/storage/nfs-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

